services:
  db:
    image: mysql:8.0 
    container_name: perpustakaan_mysql_db
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: perpustakaan_db 
      MYSQL_USER: your_db_user 
      MYSQL_PASSWORD: your_db_password
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: perpustakaan_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: your_root_password'
      PMA_PORT: 3306 
    ports:
      - "8080:80"
    depends_on:
      - db 

volumes:
  db_data:
